on: 
  pull_request:
  push:
    branches:
    - master

name: Windows Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x, 1.25.x]
        platform:
        - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Install dependencies
      shell: powershell
      run: |
        winget install --id Slik.Subversion --accept-source-agreements --accept-package-agreements
        winget install --id Mercurial.Mercurial --accept-source-agreements --accept-package-agreements
        $env:PATH = "C:\Program Files\SlikSvn\bin;C:\Program Files\Mercurial;$env:PATH"
        echo "C:\Program Files\SlikSvn\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Program Files\Mercurial" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Test
      run: go test -v
      env:
        # Skipping bzr tests on Windows as bzr does not install properly there.
        # bzr development stopped in 2017 (when last change landed). The official
        # windows installer is still bzr 2.5. The installer does not setup working
        # cacerts. This needs to be manually modified to get working. Skipping
        # tests in this environment as there are environment problems.
        SKIP_BZR: "true"
